CREATE TABLE `t_blog` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `GITHUB_NAME` varchar(255) DEFAULT NULL COMMENT 'github 名字',
  `TYPE` varchar(255) DEFAULT NULL COMMENT '文章类型',
  `TITLE` varchar(255) DEFAULT NULL COMMENT '文章标题',
  `TAG` varchar(500) DEFAULT NULL COMMENT '文章标签',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '条目创建时间',
  `URL` varchar(500) DEFAULT NULL COMMENT '文章连接',
  `GITHUB_TIME` datetime DEFAULT NULL COMMENT 'github创建时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3691 DEFAULT CHARSET=utf8;

CREATE TABLE `t_github_user` (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `GITHUB_NAME` varchar(255) DEFAULT NULL COMMENT 'github用户名',
  `GITHUB_REPOSITORY` varchar(255) DEFAULT NULL COMMENT 'github仓库',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `UPDATE_TIME` datetime DEFAULT NULL COMMENT '更新时间',
  `state` int(1) DEFAULT NULL COMMENT '是否可用',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

